### ISSUE TITLE
Voting utility functions

### ISSUE THREAD

**Issue by minahil-imtiaz** [saad-s/snapshot-y#5]
- [x] Add function to count votes 
- [x] Test count votes function 
- [x] Add function to register votes 
- [x] Test register vote function
- [x] Add strategies wrappers 
- [x] Test strategies wrappers

**Comment by saad-s** [comment]
start and end block should be editable till the voting block height is reached

**Comment by saad-s** [comment]
moving start and end blocks items to #7
