### ISSUE TITLE
Ethereum Balance strategies

### ISSUE THREAD

**Issue by minahil-imtiaz** [saad-s/snapshot-y#8]
- [x] Minimum Ethereum balance strategy 
- [x] Vanilla Ethereum strategy 
- [ ] Ethereum balance strategy at a block
- [ ] Minimum Ethereum balance strategy at a block
- [x] Add test cases

**Comment by saad-s** [comment]
`at-block` execution is not possible in Ethereum without involving oracles. This is also not supported in snapshot.
